### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kslong** [sdss/lvmdatasimulator#43]
Since this is code in development, you want folks to pull it regularly.  The documentation needs to be explicit that every time this is done, one needs to do another pip install.  

(Note that in my view this should not be necessary and somehow one should be able to set up a directory structure where one could avoid this by including certain directories in one's PYTHONPATH, etc.  That may not be possible in this case.)

**Comment by cloud182** [comment]
Hi,

I was not aware of this, I was actually pretty sure that this installation method allows you to pull the code from GitHub without reinstalling it, as long as you do not delete (or change) the directory and clone it from scratch. 

So I did some tests. I created a new, empty, conda environment and installed the code from scratch, in a separate location with respect to my development version. Then, I proceeded to fix the ETC bug, and I pushed the changes to GitHub. Finally, I pulled the new changes into the new location. The package continued to work after the pull, without installing it again, and it included the changes I applied to the code in the other location. 

If this is not your experience, can you describe to me what is happening in more detail so that I can do some more extensive tests?

**Comment by kslong** [comment]
I agree; I was able to pull the changes associated with #42, and I did not need to do a pip install for this case.  I am not sure what my issue was.  Since I am the only to report this, I will close the issue, and reopen it, if I see an example I can document.  Thank you for looking into this.
